# Builds the CPU and CUDA variants of libxgboost and xgboost packages
{% set version = "1.4.2" %}
{% set build_ext_version = version %}
{% set proc_build_number = "1" %}

{% set name = "xgboost-base" %}

package:
  name: xgboost-ext
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/xgboost
  git_tag: v{{ version }}
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fixed-a-test-failure-in-test_with_pandas.py.patch
    - 0004-Use-central-cuda-capabilities.patch  #[build_type == 'cuda']

build:

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - make
    - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
    - nccl {{ nccl }}                          #[build_type == 'cuda']
  host:
    - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
    - nccl {{ nccl }}                          #[build_type == 'cuda']

build:
  number: 4
  run_exports:
    - {{ pin_subpackage("libxgboost", max_pin="x.x.x") }}
{% if build_type == 'cuda' %}
  script_env:
    - CUDA_HOME
{% endif %}

outputs:
  - name: xgboost-proc
    version: {{ build_ext_version }}
    build:
      number: {{ proc_build_number }}
      string: {{ build_type }}
    test:
      commands:
         - exit 0
    about:
      home: https://github.com/dmlc/xgboost/
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE
      summary: Scalable, Portable and Distributed Gradient Boosting Library

  - name: libxgboost
    script: install-libxgboost.sh
    version: {{ version }}
    build:
      string: {{ build_type }}_{{ PKG_BUILDNUM }} #[build_type == 'cpu']
      string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
{% if build_type == 'cuda' %}
      script_env:
        - CUDA_HOME
{% endif %}
      run_exports:
        - {{ pin_subpackage("libxgboost", max_pin="x.x.x") }}
      track_features:
        {{ "- xgboost-cuda" if build_type == 'cuda' else "" }} 

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - make
        - git >={{ git }}
        - patch
      host:
        - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
        - nccl {{ nccl }}                          #[build_type == 'cuda']
      run:
        - cudatoolkit {{ cudatoolkit }}        #[build_type == 'cuda']
        - nccl {{ nccl }}                      #[build_type == 'cuda']
      run_constrained:
        - xgboost-proc * {{ build_type }}

    about:
      home: https://github.com/dmlc/xgboost/
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE
      summary: Scalable, Portable and Distributed Gradient Boosting Library
      description: |
        XGBoost is an optimized distributed gradient boosting library
        designed to be highly efficient, flexible and portable, for Python, R, Java,
        Scala, C++ and more.
      doc_url: https://xgboost.readthedocs.io/en/latest/
      dev_url: https://github.com/dmlc/xgboost/

  - name: xgboost
    script: install-py-xgboost.sh
    version: {{ version }}
    build:
      string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cpu']
      string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
{% if build_type == 'cuda' %}
      script_env:
        - CUDA_HOME
{% endif %}
      track_features:
        {{ "- xgboost-cuda" if build_type == 'cuda' else "" }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python {{ python }}
        - setuptools {{ setuptools }}
      run:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python {{ python }}
        - numpy {{ numpy }}
        - scipy {{ scipy }}
        - scikit-learn
      run_constrained:
        - xgboost-proc * {{ build_type }}
    test:
      files:
        - test-py-xgboost.py
      commands:
        - python test-py-xgboost.py
      imports:
        - xgboost
    about:
      home: https://github.com/dmlc/xgboost/
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE
      summary: Scalable, Portable and Distributed Gradient Boosting Library
      description: |
        XGBoost is an optimized distributed gradient boosting library
        designed to be highly efficient, flexible and portable, for Python, R, Java,
        Scala, C++ and more.

about:
  home: https://github.com/dmlc/xgboost/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Scalable, Portable and Distributed Gradient Boosting Library
  description: |
    XGBoost is an optimized distributed gradient boosting library
    designed to be highly efficient, flexible and portable, for Python, R, Java,
    Scala, C++ and more. 
  doc_url: https://xgboost.readthedocs.io/en/latest/
  dev_url: https://github.com/dmlc/xgboost/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
