# Recipe for metapackages to install CPU and CUDA versions of xgboost

{% set version = "1.3.3" %}

package:
  name: py-xgboost{{ '-cpu' if build_type == 'cpu' else '' }}
  version: {{ version }}

build:
  number: 2
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

requirements:
  run:
    - libxgboost-base {{ version }}*
    - py-xgboost-base {{ version }}*
    - _xgboost_select =={{ xgboost_select_version }}*
    - python {{ python }}
    - cudatoolkit {{ cudatoolkit }} #[build_type == 'cuda']

about:
  home: https://github.com/dmlc/xgboost/
  license: Apache-2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: A metapackage for selecting a XGBoost variant.
  description: A metapackage for selecting a XGBoost variant.
  doc_url: https://xgboost.readthedocs.io/en/latest/
  dev_url: https://github.com/dmlc/xgboost/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

